# Generated by Django 5.0.6 on 2024-07-06 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_payment_id_coffee_oreder_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coffee',
            old_name='oreder_id',
            new_name='order_id',
        ),
    ]
