# Generated by Django 5.0.6 on 2024-07-06 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_oreder_id_coffee_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffee',
            name='email',
            field=models.EmailField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
